# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: copper02.github.io
email: chainjyh@gmail.com 
description: >
	Coming soon 
baseurl: "" 
url: "https://copper02.github.io"
github_username: copper02 

# Build settings
markdown: kramdown
